package com.enderdragonanthro;

/**
 * GENERATED by tools/bbmodel_to_java.py — do not hand-edit.
 *
 * The rig's own measurements, on the common side because the eye height they
 * feed is part of the entity's dimensions and so has to agree on the server as
 * well as the client.
 */
public final class DragonRig {
    /** The rig's foot plane, and the top of the skull above it, in model units. */
    public static final float FOOT_PLANE = 96.0F;
    public static final float SKULL_HEIGHT = 133.0F;

    /**
     * Centre of the painted eyes, in model units above the foot plane, read
     * off the emissive sheet at conversion time. Paint the eyes somewhere else
     * and this follows them.
     */
    public static final float EYE_RIG_Y = 123.50F;

    /**
     * Centre of the chest, in model units above the foot plane.
     *
     * Measured off the cube named "chest" at conversion time, for the same
     * reason the eye is measured off the paint: half the hitbox height is a
     * number that refers to nothing about the model, and on a body eight blocks
     * tall it lands on the pelvis. Move the chest in Blockbench and the crystal
     * beam follows it.
     */
    public static final float HEART_RIG_Y = 99.00F;

    /** The model is authored at four times life size on the sheet. */
    public static final float AUTHORED_SCALE = 4.0F;
    /** Exactly as drawn: the head rides above the hitbox, as the canon dragon's does. */
    public static final float TRUE_SCALE = 1.0F / AUTHORED_SCALE;
    /** Trimmed so the skull tops out level with the hitbox. */
    public static final float RENDER_SCALE = 1.8F * 16.0F / SKULL_HEIGHT;

    /**
     * How far the rig reaches SIDEWAYS from its pivot, in model units.
     *
     * Measured off the rig at conversion time, not typed in. The wings are the
     * whole reason it exists: they overhang the hitbox by several blocks, and
     * Minecraft culls an entity on its BOUNDING BOX -- so a dragon stopped
     * being drawn the moment its narrow box left the view, with a wingspan of
     * it still on screen. Reported from a second player looking slightly left.
     */
    public static final float REACH_UNITS = 103.85F;

    /**
     * The same reach in blocks, for the culling box to be inflated by.
     *
     * TWO scales, and missing either one is how this gets quietly wrong: the
     * layer draws the model at TRUE_SCALE, and the renderer then multiplies
     * everything again by the entity's own SCALE attribute, which is what makes
     * a dragon eight blocks tall rather than two.
     *
     * TRUE_SCALE rather than RENDER_SCALE because it is the larger of the two
     * and the config picks between them at runtime; the bigger box is right for
     * both.
     *
     * Generous on purpose, by 1.35x. REACH_UNITS is the REST pose and the
     * wingbeat swings past it. Culling too little is an entity that blinks out
     * of existence; culling too much costs a few triangles that were off screen
     * anyway. The asymmetry between those two mistakes is the whole argument.
     */
    public static float cullReach(float entityScale) {
        return REACH_UNITS / 16.0F * TRUE_SCALE * entityScale * 1.35F;
    }

    private DragonRig() {
    }

    /**
     * The rig puts the foot plane at FOOT_PLANE, which only lands on the ground
     * at a scale of exactly 0.25. Any other scale lifts the whole dragon, so
     * the layer drops it back by this much before drawing.
     */
    public static float groundOffset(float scale) {
        return 24.0F - FOOT_PLANE * scale;
    }

    /**
     * The eye height, as a fraction of hitbox height, that lands the camera on
     * the painted eyes.
     *
     * The entity scale cancels — the eye is a fraction of the hitbox and the
     * model is a multiple of the same scale — so this depends on the render
     * scale alone. That cancellation is exactly why vanilla's fixed 0.9 can
     * never track the model: nothing in it refers to the rig.
     */
    public static double eyeRatio(float renderScale) {
        return EYE_RIG_Y * renderScale / (16.0 * 1.8);
    }

    /**
     * The heart's height, as a fraction of hitbox height.
     *
     * Same derivation as {@link #eyeRatio} and the same cancellation: the
     * entity scale drops out, because the point is a fraction of the hitbox and
     * the model is a multiple of the same scale.
     */
    public static double heartRatio(float renderScale) {
        return HEART_RIG_Y * renderScale / (16.0 * 1.8);
    }
}
