package com.enderdragonanthro;

/**
 * GENERATED by tools/bbmodel_to_java.py — do not hand-edit.
 *
 * The rig's own measurements, on the common side because the eye height they
 * feed is part of the entity's dimensions and so has to agree on the server as
 * well as the client.
 */
public final class DragonRig {
    /** The rig's foot plane, and the top of the skull above it, in model units. */
    public static final float FOOT_PLANE = 96.0F;
    public static final float SKULL_HEIGHT = 133.0F;

    /**
     * Centre of the painted eyes, in model units above the foot plane, read
     * off the emissive sheet at conversion time. Paint the eyes somewhere else
     * and this follows them.
     */
    public static final float EYE_RIG_Y = 123.50F;

    /** The model is authored at four times life size on the sheet. */
    public static final float AUTHORED_SCALE = 4.0F;
    /** Exactly as drawn: the head rides above the hitbox, as the canon dragon's does. */
    public static final float TRUE_SCALE = 1.0F / AUTHORED_SCALE;
    /** Trimmed so the skull tops out level with the hitbox. */
    public static final float RENDER_SCALE = 1.8F * 16.0F / SKULL_HEIGHT;

    private DragonRig() {
    }

    /**
     * The rig puts the foot plane at FOOT_PLANE, which only lands on the ground
     * at a scale of exactly 0.25. Any other scale lifts the whole dragon, so
     * the layer drops it back by this much before drawing.
     */
    public static float groundOffset(float scale) {
        return 24.0F - FOOT_PLANE * scale;
    }

    /**
     * The eye height, as a fraction of hitbox height, that lands the camera on
     * the painted eyes.
     *
     * The entity scale cancels — the eye is a fraction of the hitbox and the
     * model is a multiple of the same scale — so this depends on the render
     * scale alone. That cancellation is exactly why vanilla's fixed 0.9 can
     * never track the model: nothing in it refers to the rig.
     */
    public static double eyeRatio(float renderScale) {
        return EYE_RIG_Y * renderScale / (16.0 * 1.8);
    }
}
