package com.enderdragonanthro.client.model;

import com.enderdragonanthro.EnderdragonAnthro;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.PlayerModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.player.AbstractClientPlayer;
import net.minecraft.client.renderer.texture.OverlayTexture;

/**
 * The anthro dragon. GENERATED by tools/bbmodel_to_java.py from
 * art/dragon_form.bbmodel — do not hand-edit; re-run the converter instead.
 *
 * Authored at 4x on a 512x512 sheet and drawn at {@link #RENDER_SCALE},
 * which both restores real size and buys one texel per model unit. The six
 * root parts keep the player's bone names and copy their poses every frame,
 * so all vanilla animation drives this body.
 */
public class DragonFormModel {
    public static final ModelLayerLocation LAYER =
            new ModelLayerLocation(EnderdragonAnthro.id("dragon_form"), "main");

    /** Model units are 4x final units. */
    public static final float AUTHOR_SCALE = 4.0F;

    /**
     * 0.25 would be an exact 4x undo. The model stands 136 units to the top of
     * the skull, which at a plain 0.25 renders 9.44 blocks tall against an
     * 8-block hitbox, so it is trimmed by 8/9.44. Horn tips still rise a little
     * above the hitbox, which is deliberate — the canon dragon's wings
     * overshoot its hitbox too.
     */
    public static final float RENDER_SCALE = 0.2118F;

    /**
     * The authoring rig puts the foot plane at y=96, which lands on the ground
     * only at a scale of exactly 0.25. Trimming to RENDER_SCALE lifts the whole
     * model, so the layer drops it back by this much (in rendered units) before
     * scaling. Without it the dragon hovers about a block off the floor.
     */
    public static final float GROUND_OFFSET = 24.0F - 96.0F * RENDER_SCALE;

    private static final float[] BASE_HEAD = {0.000F, -13.000F, 0.000F};
    private static final float[] BASE_BODY = {0.000F, -13.000F, 0.000F};
    private static final float[] BASE_RIGHT_ARM = {-20.000F, -5.000F, 2.000F};
    private static final float[] BASE_LEFT_ARM = {20.000F, -5.000F, 2.000F};
    private static final float[] BASE_RIGHT_LEG = {-7.600F, 35.000F, 0.000F};
    private static final float[] BASE_LEFT_LEG = {7.600F, 35.000F, 0.000F};

    // the vanilla player pivots these parts track
    private static final float[] V_HEAD = {0.0F, 0.0F, 0.0F};
    private static final float[] V_BODY = {0.0F, 0.0F, 0.0F};
    private static final float[] V_RIGHT_ARM = {-5.0F, 2.0F, 0.0F};
    private static final float[] V_LEFT_ARM = {5.0F, 2.0F, 0.0F};
    private static final float[] V_RIGHT_LEG = {-1.9F, 12.0F, 0.0F};
    private static final float[] V_LEFT_LEG = {1.9F, 12.0F, 0.0F};

    private final ModelPart root;
    private final ModelPart head;
    private final ModelPart body;
    private final ModelPart rightArm;
    private final ModelPart leftArm;
    private final ModelPart rightLeg;
    private final ModelPart leftLeg;

    public DragonFormModel(ModelPart root) {
        this.root = root;
        this.head = root.getChild("head");
        this.body = root.getChild("body");
        this.rightArm = root.getChild("right_arm");
        this.leftArm = root.getChild("left_arm");
        this.rightLeg = root.getChild("right_leg");
        this.leftLeg = root.getChild("left_leg");
    }

    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

        // ---- head ----
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create()
                        .texOffs(0, 20).addBox(-8.000F, -8.000F, -8.000F, 16.000F, 14.000F, 16.000F),
                PartPose.offset(0.000F, -13.000F, 0.000F));
        head.addOrReplaceChild("head_spin", CubeListBuilder.create()
                        .texOffs(284, 384).addBox(-2.000F, -3.000F, -3.000F, 4.000F, 6.000F, 6.000F),
                PartPose.offsetAndRotation(0.000F, -19.000F, 7.786F, 0.7854F, 0.0000F, -0.0000F));
        head.addOrReplaceChild("head_spin_", CubeListBuilder.create()
                        .texOffs(306, 384).addBox(-2.000F, -4.000F, -4.000F, 3.000F, 6.000F, 6.000F),
                PartPose.offsetAndRotation(0.500F, -23.000F, 8.200F, 0.7854F, 0.0000F, -0.0000F));
        head.addOrReplaceChild("head_spin__", CubeListBuilder.create()
                        .texOffs(284, 384).addBox(-2.000F, -3.000F, -3.000F, 4.000F, 6.000F, 6.000F),
                PartPose.offsetAndRotation(0.000F, -13.000F, 7.786F, 0.7854F, 0.0000F, -0.0000F));
        head.addOrReplaceChild("head_spin___", CubeListBuilder.create()
                        .texOffs(284, 384).addBox(-2.000F, -3.000F, -3.000F, 4.000F, 6.000F, 6.000F),
                PartPose.offsetAndRotation(0.000F, -5.000F, 7.786F, 0.7854F, 0.0000F, -0.0000F));
        PartDefinition crown_spike_right = head.addOrReplaceChild("crown_spike_right", CubeListBuilder.create(),
                PartPose.offsetAndRotation(-5.189F, -20.000F, 9.749F, 0.2563F, 0.1652F, -0.0870F));
        crown_spike_right.addOrReplaceChild("crown_spike_right_spin", CubeListBuilder.create()
                        .texOffs(95, 0).addBox(-2.000F, -1.500F, -6.500F, 4.000F, 3.000F, 13.000F),
                PartPose.offsetAndRotation(0.883F, -8.680F, 4.136F, 0.1137F, -0.1298F, 0.1320F));
        crown_spike_right.addOrReplaceChild("crown_spike_right_spin_", CubeListBuilder.create()
                        .texOffs(41, 126).addBox(-3.000F, -2.500F, -2.500F, 6.000F, 5.000F, 5.000F),
                PartPose.offsetAndRotation(2.109F, -5.408F, -7.400F, 0.4204F, -0.1402F, 0.1206F));
        crown_spike_right.addOrReplaceChild("crown_spike_right_spin__", CubeListBuilder.create()
                        .texOffs(96, 0).addBox(-2.500F, -2.000F, -5.000F, 5.000F, 4.000F, 10.000F),
                PartPose.offsetAndRotation(1.625F, -7.270F, -2.493F, 0.2883F, -0.1298F, 0.1320F));
        PartDefinition nape_spike_right = head.addOrReplaceChild("nape_spike_right", CubeListBuilder.create(),
                PartPose.offsetAndRotation(-5.592F, -9.597F, 6.425F, 0.5074F, 0.3000F, -0.0000F));
        nape_spike_right.addOrReplaceChild("nape_spike_right_spin", CubeListBuilder.create()
                        .texOffs(82, 128).addBox(-2.000F, -2.000F, -5.000F, 4.000F, 4.000F, 10.000F),
                PartPose.offsetAndRotation(1.017F, -4.268F, -4.681F, -0.3054F, -0.5672F, -0.0000F));
        nape_spike_right.addOrReplaceChild("nape_spike_right_spin_", CubeListBuilder.create()
                        .mirror(true).texOffs(96, 0).addBox(-1.500F, -1.500F, -5.000F, 3.000F, 3.000F, 10.000F),
                PartPose.offsetAndRotation(-3.562F, -1.370F, 2.508F, -0.3054F, -0.5672F, -0.0000F));
        PartDefinition crown_spike_left = head.addOrReplaceChild("crown_spike_left", CubeListBuilder.create(),
                PartPose.offsetAndRotation(5.189F, -20.000F, 9.749F, 0.2563F, -0.1652F, 0.0870F));
        crown_spike_left.addOrReplaceChild("crown_spike_left_spin", CubeListBuilder.create()
                        .mirror(true).texOffs(97, 0).addBox(-2.500F, -2.000F, -5.000F, 5.000F, 4.000F, 10.000F),
                PartPose.offsetAndRotation(-1.625F, -7.270F, -2.493F, 0.2883F, 0.1298F, -0.1320F));
        crown_spike_left.addOrReplaceChild("crown_spike_left_spin_", CubeListBuilder.create()
                        .mirror(true).texOffs(49, 131).addBox(-3.000F, -2.500F, -2.500F, 6.000F, 5.000F, 5.000F),
                PartPose.offsetAndRotation(-2.109F, -5.408F, -7.400F, 0.4204F, 0.1402F, -0.1206F));
        crown_spike_left.addOrReplaceChild("crown_spike_left_spin__", CubeListBuilder.create()
                        .mirror(true).texOffs(248, 384).addBox(-2.000F, -1.500F, -6.500F, 4.000F, 3.000F, 13.000F),
                PartPose.offsetAndRotation(-0.883F, -8.680F, 4.136F, 0.1137F, 0.1298F, -0.1320F));
        PartDefinition nape_spike_left = head.addOrReplaceChild("nape_spike_left", CubeListBuilder.create(),
                PartPose.offsetAndRotation(5.600F, -16.000F, 6.400F, 0.9001F, -0.3000F, -0.0000F));
        nape_spike_left.addOrReplaceChild("nape_spike_left_spin", CubeListBuilder.create()
                        .texOffs(96, 0).addBox(-1.500F, -1.500F, -5.000F, 3.000F, 3.000F, 10.000F),
                PartPose.offsetAndRotation(3.562F, -0.497F, 2.022F, -0.3054F, 0.5672F, -0.0000F));
        nape_spike_left.addOrReplaceChild("nape_spike_left_spin_", CubeListBuilder.create()
                        .texOffs(81, 127).addBox(-2.000F, -2.000F, -5.000F, 4.000F, 4.000F, 10.000F),
                PartPose.offsetAndRotation(-1.017F, -3.394F, -5.167F, -0.3054F, 0.5672F, -0.0000F));
        PartDefinition nape_spike_left2 = head.addOrReplaceChild("nape_spike_left2", CubeListBuilder.create(),
                PartPose.offsetAndRotation(5.592F, -9.597F, 6.425F, 0.5074F, -0.3000F, -0.0000F));
        nape_spike_left2.addOrReplaceChild("nape_spike_left2_spin", CubeListBuilder.create()
                        .texOffs(96, 0).addBox(-1.500F, -1.500F, -5.000F, 3.000F, 3.000F, 10.000F),
                PartPose.offsetAndRotation(3.562F, -1.370F, 2.508F, -0.3054F, 0.5672F, -0.0000F));
        nape_spike_left2.addOrReplaceChild("nape_spike_left2_spin_", CubeListBuilder.create()
                        .texOffs(81, 127).addBox(-2.000F, -2.000F, -5.000F, 4.000F, 4.000F, 10.000F),
                PartPose.offsetAndRotation(-1.017F, -4.268F, -4.681F, -0.3054F, 0.5672F, -0.0000F));
        PartDefinition skull = head.addOrReplaceChild("skull", CubeListBuilder.create()
                        .texOffs(0, 258).addBox(-8.000F, -8.000F, -10.000F, 16.000F, 16.000F, 18.000F)
                        .texOffs(67, 257).addBox(-6.000F, 0.000F, -24.000F, 12.000F, 5.000F, 19.000F),
                PartPose.offset(0.000F, -16.000F, 0.000F));
        skull.addOrReplaceChild("jaw", CubeListBuilder.create()
                        .texOffs(138, 257).addBox(-6.000F, 1.000F, -16.000F, 12.000F, 4.000F, 19.000F),
                PartPose.offset(0.000F, 4.000F, -8.000F));
        PartDefinition nape_spike_right2 = head.addOrReplaceChild("nape_spike_right2", CubeListBuilder.create(),
                PartPose.offsetAndRotation(-5.600F, -16.000F, 6.400F, 0.9001F, 0.3000F, -0.0000F));
        nape_spike_right2.addOrReplaceChild("nape_spike_right2_spin", CubeListBuilder.create()
                        .mirror(true).texOffs(96, 0).addBox(-1.500F, -1.500F, -5.000F, 3.000F, 3.000F, 10.000F),
                PartPose.offsetAndRotation(-3.562F, -0.497F, 2.022F, -0.3054F, -0.5672F, -0.0000F));
        nape_spike_right2.addOrReplaceChild("nape_spike_right2_spin_", CubeListBuilder.create()
                        .mirror(true).texOffs(81, 127).addBox(-2.000F, -2.000F, -5.000F, 4.000F, 4.000F, 10.000F),
                PartPose.offsetAndRotation(1.017F, -3.394F, -5.167F, -0.3054F, -0.5672F, -0.0000F));

        // ---- body ----
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                        .texOffs(0, 72).addBox(-20.000F, 0.000F, -10.000F, 40.000F, 20.000F, 20.000F)
                        .texOffs(206, 70).addBox(-16.000F, 20.000F, -8.000F, 32.000F, 16.000F, 18.000F)
                        .texOffs(308, 72).addBox(-10.000F, 20.000F, -10.000F, 20.000F, 16.000F, 4.000F)
                        .texOffs(0, 120).addBox(-16.000F, 36.000F, -10.000F, 32.000F, 12.000F, 20.000F),
                PartPose.offset(0.000F, -13.000F, 0.000F));
        body.addOrReplaceChild("body_spin", CubeListBuilder.create()
                        .texOffs(219, 85).addBox(-10.500F, -3.500F, -5.500F, 24.000F, 19.000F, 11.000F),
                PartPose.offsetAndRotation(-13.284F, -0.781F, 2.685F, -0.0000F, 0.0858F, -0.2967F));
        body.addOrReplaceChild("body_spin_", CubeListBuilder.create()
                        .texOffs(215, 78).addBox(-8.000F, -3.500F, -5.500F, 16.000F, 12.000F, 18.000F),
                PartPose.offsetAndRotation(-14.559F, 26.548F, -2.539F, -0.0000F, 0.0000F, -1.8282F));
        body.addOrReplaceChild("body_spin__", CubeListBuilder.create()
                        .mirror(true).texOffs(222, 85).addBox(-8.000F, -3.500F, -5.500F, 16.000F, 12.000F, 18.000F),
                PartPose.offsetAndRotation(14.559F, 26.548F, -2.539F, -0.0000F, 0.0000F, 1.8282F));
        body.addOrReplaceChild("body_spin___", CubeListBuilder.create()
                        .texOffs(0, 384).addBox(-2.000F, -3.500F, -3.500F, 4.000F, 7.000F, 7.000F),
                PartPose.offsetAndRotation(0.000F, 4.000F, 9.279F, -0.7854F, 0.0000F, -0.0000F));
        body.addOrReplaceChild("body_spin____", CubeListBuilder.create()
                        .texOffs(24, 384).addBox(-2.000F, -3.500F, -3.500F, 4.000F, 7.000F, 7.000F),
                PartPose.offsetAndRotation(0.000F, 12.000F, 10.279F, -0.7854F, 0.0000F, -0.0000F));
        body.addOrReplaceChild("body_spin_____", CubeListBuilder.create()
                        .texOffs(48, 384).addBox(-2.000F, -3.500F, -3.500F, 4.000F, 7.000F, 7.000F),
                PartPose.offsetAndRotation(0.000F, 20.000F, 9.479F, -0.7854F, 0.0000F, -0.0000F));
        body.addOrReplaceChild("body_spin______", CubeListBuilder.create()
                        .texOffs(72, 384).addBox(-2.000F, -3.500F, -3.500F, 4.000F, 7.000F, 7.000F),
                PartPose.offsetAndRotation(0.000F, 28.000F, 8.679F, -0.7854F, 0.0000F, -0.0000F));
        body.addOrReplaceChild("body_spin_______", CubeListBuilder.create()
                        .mirror(true).texOffs(222, 85).addBox(-13.500F, -3.500F, -5.500F, 24.000F, 19.000F, 11.000F),
                PartPose.offsetAndRotation(13.284F, -0.781F, 2.685F, -0.0000F, -0.0858F, 0.2967F));
        PartDefinition tail1 = body.addOrReplaceChild("tail1", CubeListBuilder.create()
                        .texOffs(108, 120).addBox(-6.000F, -6.000F, 0.000F, 12.000F, 12.000F, 28.000F),
                PartPose.offsetAndRotation(0.000F, 35.000F, 6.000F, -0.9001F, 0.0000F, -0.0000F));
        tail1.addOrReplaceChild("tail1_spin", CubeListBuilder.create()
                        .texOffs(328, 128).addBox(-2.000F, -4.000F, -4.000F, 4.000F, 8.000F, 8.000F),
                PartPose.offsetAndRotation(0.000F, -5.800F, 7.505F, 0.8290F, 0.0000F, -0.0000F));
        tail1.addOrReplaceChild("tail1_spin_", CubeListBuilder.create()
                        .texOffs(328, 128).addBox(-2.000F, -4.000F, -4.000F, 4.000F, 8.000F, 8.000F),
                PartPose.offsetAndRotation(0.000F, -5.851F, 20.311F, 0.8290F, 0.0000F, -0.0000F));
        PartDefinition tail2 = tail1.addOrReplaceChild("tail2", CubeListBuilder.create()
                        .texOffs(189, 119).addBox(-5.700F, -4.532F, -1.277F, 11.000F, 10.000F, 25.000F),
                PartPose.offsetAndRotation(0.000F, 0.000F, 26.400F, 0.4199F, 0.0000F, -0.0000F));
        tail2.addOrReplaceChild("tail2_spin", CubeListBuilder.create()
                        .texOffs(328, 128).addBox(-2.000F, -4.000F, -4.000F, 4.000F, 8.000F, 8.000F),
                PartPose.offsetAndRotation(0.000F, -2.524F, 9.173F, 0.8290F, 0.0000F, -0.0000F));
        tail2.addOrReplaceChild("tail2_spin_", CubeListBuilder.create()
                        .texOffs(328, 128).addBox(-2.000F, -4.000F, -4.000F, 4.000F, 8.000F, 8.000F),
                PartPose.offsetAndRotation(0.000F, -2.672F, 18.116F, 0.8290F, 0.0000F, -0.0000F));
        PartDefinition tail3 = tail2.addOrReplaceChild("tail3", CubeListBuilder.create()
                        .texOffs(239, 102).addBox(-5.200F, -3.689F, -0.125F, 10.000F, 9.000F, 42.000F),
                PartPose.offsetAndRotation(0.000F, 0.000F, 22.400F, 0.3000F, 0.0000F, -0.0000F));
        tail3.addOrReplaceChild("tail3_spin", CubeListBuilder.create()
                        .texOffs(328, 128).addBox(-2.000F, -4.000F, -4.000F, 4.000F, 8.000F, 8.000F),
                PartPose.offsetAndRotation(0.000F, -1.870F, 8.059F, 0.8290F, 0.0000F, -0.0000F));
        tail3.addOrReplaceChild("tail3_spin_", CubeListBuilder.create()
                        .texOffs(328, 128).addBox(-2.000F, -4.000F, -4.000F, 4.000F, 8.000F, 8.000F),
                PartPose.offsetAndRotation(0.000F, -2.105F, 17.164F, 0.8290F, 0.0000F, -0.0000F));
        tail3.addOrReplaceChild("tail3_spin__", CubeListBuilder.create()
                        .texOffs(328, 128).addBox(-2.000F, -4.000F, -4.000F, 4.000F, 8.000F, 8.000F),
                PartPose.offsetAndRotation(0.000F, -2.143F, 26.305F, 0.8290F, 0.0000F, -0.0000F));
        tail3.addOrReplaceChild("tail3_spin___", CubeListBuilder.create()
                        .texOffs(328, 128).addBox(-2.000F, -4.000F, -4.000F, 4.000F, 8.000F, 8.000F),
                PartPose.offsetAndRotation(0.000F, -1.788F, 35.518F, 0.8290F, 0.0000F, -0.0000F));

        // ---- right_arm ----
        PartDefinition right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                        .texOffs(76, 164).addBox(-17.000F, -1.000F, -8.000F, 16.000F, 17.000F, 16.000F)
                        .texOffs(208, 164).addBox(-16.000F, 16.000F, -7.500F, 14.000F, 18.000F, 15.000F)
                        .texOffs(268, 164).addBox(-15.500F, 32.000F, -7.000F, 15.000F, 14.000F, 14.000F),
                PartPose.offset(-20.000F, -5.000F, 2.000F));
        right_arm.addOrReplaceChild("right_arm_spin", CubeListBuilder.create()
                        .texOffs(96, 384).addBox(-9.500F, -6.000F, -9.000F, 19.000F, 12.000F, 18.000F),
                PartPose.offsetAndRotation(-6.726F, -1.708F, 0.000F, -0.0000F, 0.0000F, -0.4800F));

        // ---- left_arm ----
        PartDefinition left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                        .texOffs(76, 164).addBox(1.000F, -1.000F, -8.000F, 16.000F, 17.000F, 16.000F)
                        .texOffs(208, 164).addBox(2.000F, 16.000F, -7.500F, 14.000F, 18.000F, 15.000F)
                        .mirror(true).texOffs(268, 164).addBox(0.500F, 32.000F, -7.000F, 15.000F, 14.000F, 14.000F)
                        .mirror(false),
                PartPose.offset(20.000F, -5.000F, 2.000F));
        left_arm.addOrReplaceChild("left_arm_spin", CubeListBuilder.create()
                        .mirror(true).texOffs(172, 384).addBox(-9.500F, -6.000F, -9.000F, 19.000F, 12.000F, 18.000F),
                PartPose.offsetAndRotation(6.726F, -1.708F, 0.000F, -0.0000F, 0.0000F, 0.4800F));

        // ---- right_leg ----
        PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                        .texOffs(2, 200).addBox(-9.000F, 0.000F, -9.000F, 16.000F, 29.000F, 18.000F)
                        .texOffs(116, 200).addBox(-9.000F, 29.000F, -8.000F, 16.000F, 24.000F, 16.000F)
                        .mirror(true).texOffs(222, 202).addBox(-9.000F, 53.000F, -9.400F, 16.000F, 8.000F, 18.000F)
                        .mirror(false),
                PartPose.offset(-7.600F, 35.000F, 0.000F));
        right_leg.addOrReplaceChild("right_leg_spin", CubeListBuilder.create()
                        .texOffs(222, 202).addBox(-8.000F, -5.000F, -9.000F, 16.000F, 8.000F, 18.000F),
                PartPose.offsetAndRotation(-1.000F, 57.000F, -5.400F, 0.3054F, 0.0000F, -0.0000F));
        right_leg.addOrReplaceChild("right_leg_spin_", CubeListBuilder.create()
                        .texOffs(296, 200).addBox(-3.000F, -3.000F, -2.000F, 4.000F, 9.000F, 4.000F),
                PartPose.offsetAndRotation(-5.200F, 58.000F, -15.000F, -1.2217F, 0.0000F, -0.0000F));
        right_leg.addOrReplaceChild("right_leg_spin__", CubeListBuilder.create()
                        .texOffs(296, 200).addBox(-3.000F, -3.000F, -2.000F, 4.000F, 9.000F, 4.000F),
                PartPose.offsetAndRotation(0.000F, 58.000F, -15.000F, -1.2217F, 0.0000F, -0.0000F));
        right_leg.addOrReplaceChild("right_leg_spin___", CubeListBuilder.create()
                        .texOffs(296, 200).addBox(-3.000F, -3.000F, -2.000F, 4.000F, 9.000F, 4.000F),
                PartPose.offsetAndRotation(5.200F, 58.000F, -15.000F, -1.2217F, 0.0000F, -0.0000F));

        // ---- left_leg ----
        PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                        .texOffs(0, 200).addBox(-7.000F, 0.000F, -9.000F, 16.000F, 29.000F, 18.000F)
                        .texOffs(116, 200).addBox(-7.000F, 29.000F, -8.000F, 16.000F, 24.000F, 16.000F)
                        .mirror(true).texOffs(222, 202).addBox(-7.000F, 53.000F, -9.400F, 16.000F, 8.000F, 18.000F)
                        .mirror(false),
                PartPose.offset(7.600F, 35.000F, 0.000F));
        left_leg.addOrReplaceChild("left_leg_spin", CubeListBuilder.create()
                        .mirror(true).texOffs(296, 200).addBox(-1.000F, -3.000F, -2.000F, 4.000F, 9.000F, 4.000F),
                PartPose.offsetAndRotation(-5.200F, 58.000F, -15.000F, -1.2217F, 0.0000F, -0.0000F));
        left_leg.addOrReplaceChild("left_leg_spin_", CubeListBuilder.create()
                        .mirror(true).texOffs(296, 200).addBox(-1.000F, -3.000F, -2.000F, 4.000F, 9.000F, 4.000F),
                PartPose.offsetAndRotation(5.200F, 58.000F, -15.000F, -1.2217F, 0.0000F, -0.0000F));
        left_leg.addOrReplaceChild("left_leg_spin__", CubeListBuilder.create()
                        .mirror(true).texOffs(296, 200).addBox(-1.000F, -3.000F, -2.000F, 4.000F, 9.000F, 4.000F),
                PartPose.offsetAndRotation(0.000F, 58.000F, -15.000F, -1.2217F, 0.0000F, -0.0000F));
        left_leg.addOrReplaceChild("left_leg_spin___", CubeListBuilder.create()
                        .texOffs(222, 202).addBox(-8.000F, -5.000F, -9.000F, 16.000F, 8.000F, 18.000F),
                PartPose.offsetAndRotation(1.000F, 57.000F, -5.400F, 0.3054F, 0.0000F, -0.0000F));

        // ---- wings: re-parented onto body so they follow the torso ----
        PartDefinition wing_right = body.addOrReplaceChild("wing_right", CubeListBuilder.create()
                        .mirror(true).texOffs(0, 300).addBox(-56.000F, -4.000F, -4.000F, 56.000F, 8.000F, 8.000F)
                        .texOffs(0, 320).addBox(-56.000F, 0.000F, 4.000F, 56.000F, 0.000F, 56.000F)
                        .mirror(false),
                PartPose.offsetAndRotation(-16.000F, 6.000F, 8.000F, -1.3355F, 0.8951F, 0.3530F));
        wing_right.addOrReplaceChild("wing_tip_right", CubeListBuilder.create()
                        .mirror(true).texOffs(132, 300).addBox(-56.000F, -2.000F, -2.000F, 56.000F, 4.000F, 4.000F)
                        .texOffs(256, 320).addBox(-56.000F, 0.000F, 2.000F, 56.000F, 0.000F, 56.000F)
                        .mirror(false),
                PartPose.offset(-56.000F, 0.000F, 0.000F));
        PartDefinition wing_left = body.addOrReplaceChild("wing_left", CubeListBuilder.create()
                        .texOffs(0, 300).addBox(0.000F, -4.000F, -4.000F, 56.000F, 8.000F, 8.000F)
                        .texOffs(0, 320).addBox(0.000F, 0.000F, 4.000F, 56.000F, 0.000F, 56.000F),
                PartPose.offsetAndRotation(16.000F, 6.000F, 8.000F, -1.3355F, -0.8951F, -0.3530F));
        wing_left.addOrReplaceChild("wing_tip_left", CubeListBuilder.create()
                        .texOffs(132, 300).addBox(0.000F, -2.000F, -2.000F, 56.000F, 4.000F, 4.000F)
                        .texOffs(256, 320).addBox(0.000F, 0.000F, 2.000F, 56.000F, 0.000F, 56.000F),
                PartPose.offset(56.000F, 0.000F, 0.000F));

        return LayerDefinition.create(mesh, 512, 512);
    }

    /**
     * Ride the vanilla skeleton. Positions are applied as a DELTA from the
     * player's own rest pivots rather than copied outright, because this
     * model's pivots are not simply the player's times four — the legs are
     * longer, which lifts everything. Copying outright would tear the body
     * apart; the delta still picks up animated offsets such as sneaking.
     */
    public void copyPose(PlayerModel<AbstractClientPlayer> m) {
        apply(this.head, m.head, BASE_HEAD, V_HEAD);
        apply(this.body, m.body, BASE_BODY, V_BODY);
        apply(this.rightArm, m.rightArm, BASE_RIGHT_ARM, V_RIGHT_ARM);
        apply(this.leftArm, m.leftArm, BASE_LEFT_ARM, V_LEFT_ARM);
        apply(this.rightLeg, m.rightLeg, BASE_RIGHT_LEG, V_RIGHT_LEG);
        apply(this.leftLeg, m.leftLeg, BASE_LEFT_LEG, V_LEFT_LEG);
    }

    private static void apply(ModelPart target, ModelPart source, float[] base, float[] vanilla) {
        target.copyFrom(source);
        target.x = base[0] + (source.x - vanilla[0]) * AUTHOR_SCALE;
        target.y = base[1] + (source.y - vanilla[1]) * AUTHOR_SCALE;
        target.z = base[2] + (source.z - vanilla[2]) * AUTHOR_SCALE;
    }

    public void render(PoseStack poseStack, VertexConsumer buffer, int light) {
        this.root.render(poseStack, buffer, light, OverlayTexture.NO_OVERLAY);
    }
}
