package com.enderdragonanthro.client.model;

import com.enderdragonanthro.EnderdragonAnthro;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.renderer.texture.OverlayTexture;
import net.minecraft.world.entity.LivingEntity;

/**
 * GENERATED by tools/shade_to_java.py from art/shade_base.bbmodel.
 * Do not hand-edit: the next conversion overwrites it.
 *
 * One of the court, drawn over a vanilla enderman. The bones are named for
 * HumanoidModel's, which EndermanModel extends, so copyPose can hand this rig
 * the vanilla animation and every walk cycle and carry pose comes free.
 */
public class ShadeModel {
    public static final ModelLayerLocation LAYER =
            new ModelLayerLocation(EnderdragonAnthro.id("shade"), "main");

    /** The rig is drawn 2x oversize to buy texel density; undo it here. */
    public static final float AUTHOR_SCALE = 2.0F;
    public static final float TRUE_SCALE = 1.0F / AUTHOR_SCALE;
    /** Java y of the foot plane, before that scale. */
    public static final float FOOT_PLANE = 95.600F;

    private final ModelPart root;
    private final ModelPart head;
    private final ModelPart body;
    private final ModelPart rightArm;
    private final ModelPart leftArm;
    private final ModelPart rightLeg;
    private final ModelPart leftLeg;

    public ShadeModel(ModelPart root) {
        this.root = root;
        this.head = root.getChild("head");
        this.body = root.getChild("body");
        this.rightArm = root.getChild("right_arm");
        this.leftArm = root.getChild("left_arm");
        this.rightLeg = root.getChild("right_leg");
        this.leftLeg = root.getChild("left_leg");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create()
                        .texOffs(0, 63).addBox(-8.000F, -17.000F, -8.000F, 16.000F, 16.000F, 16.000F),
                PartPose.offset(0.000F, 18.000F, 0.000F));

        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                        .texOffs(0, 96).addBox(-3.000F, -30.000F, -3.000F, 6.000F, 8.000F, 6.000F),
                PartPose.offset(0.000F, 44.000F, 0.000F));
        body.addOrReplaceChild("body_0", CubeListBuilder.create()
                        .texOffs(91, 0).addBox(-4.000F, -13.000F, -4.000F, 10.000F, 26.000F, 8.000F),
                PartPose.offsetAndRotation(-1.000F, -13.000F, 0.000F, -0.0000F, 0.0000F, 0.3665F));
        body.addOrReplaceChild("body_1", CubeListBuilder.create()
                        .mirror(true).texOffs(91, 0).addBox(-6.000F, -13.000F, -4.000F, 10.000F, 26.000F, 8.000F),
                PartPose.offsetAndRotation(1.000F, -13.000F, 0.000F, -0.0000F, 0.0000F, -0.3665F));
        body.addOrReplaceChild("body_2", CubeListBuilder.create()
                        .texOffs(65, 63).addBox(-9.000F, -4.000F, -2.000F, 16.000F, 8.000F, 8.000F),
                PartPose.offsetAndRotation(1.000F, -19.800F, -6.400F, -1.0472F, 0.0000F, -0.0000F));

        PartDefinition right_arm = root.addOrReplaceChild("right_arm", CubeListBuilder.create(),
                PartPose.offset(-8.000F, 20.000F, 0.000F));
        right_arm.addOrReplaceChild("right_arm_0", CubeListBuilder.create()
                        .texOffs(66, 0).addBox(-5.000F, 0.000F, -2.000F, 5.000F, 36.000F, 6.000F),
                PartPose.offsetAndRotation(4.000F, 2.000F, -1.000F, -0.0000F, 0.0000F, 0.2793F));

        PartDefinition left_arm = root.addOrReplaceChild("left_arm", CubeListBuilder.create(),
                PartPose.offset(8.000F, 20.000F, 0.000F));
        left_arm.addOrReplaceChild("left_arm_0", CubeListBuilder.create()
                        .mirror(true).texOffs(66, 0).addBox(0.000F, 0.000F, -2.000F, 5.000F, 36.000F, 6.000F),
                PartPose.offsetAndRotation(-4.000F, 2.000F, -1.000F, -0.0000F, 0.0000F, -0.2793F));

        PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create(),
                PartPose.offset(-4.000F, 44.000F, 0.000F));
        right_leg.addOrReplaceChild("right_leg_0", CubeListBuilder.create()
                        .texOffs(33, 0).addBox(-4.000F, -2.000F, -4.000F, 8.000F, 54.000F, 8.000F),
                PartPose.offsetAndRotation(-1.300F, -0.400F, 0.000F, -0.0000F, 0.0000F, -0.0175F));

        PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create(),
                PartPose.offset(4.000F, 44.000F, 0.000F));
        left_leg.addOrReplaceChild("left_leg_0", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(-4.000F, -2.000F, -4.000F, 8.000F, 54.000F, 8.000F),
                PartPose.offsetAndRotation(1.300F, -0.400F, 0.000F, -0.0000F, 0.0000F, 0.0175F));

        return LayerDefinition.create(mesh, 128, 128);
    }

    /**
     * Take the vanilla enderman's pose.
     *
     * Rotations only. Positions are this rig's own, because a shade's shoulders
     * and hips are nowhere near an enderman's -- copying those outright tears
     * the body apart, which is the same lesson the dragon's copyPose records.
     */
    public void copyPose(HumanoidModel<? extends LivingEntity> from) {
        rot(this.head, from.head);
        rot(this.body, from.body);
        rot(this.rightArm, from.rightArm);
        rot(this.leftArm, from.leftArm);
        rot(this.rightLeg, from.rightLeg);
        rot(this.leftLeg, from.leftLeg);
    }

    private static void rot(ModelPart target, ModelPart source) {
        target.xRot = source.xRot;
        target.yRot = source.yRot;
        target.zRot = source.zRot;
    }

    /**
     * The rig puts its feet at FOOT_PLANE, which only lands on the ground at a
     * scale of exactly one over AUTHOR_SCALE. Any other scale lifts the whole
     * body, so the layer drops it back by this much before drawing.
     */
    public static float groundOffset(float scale) {
        return 24.0F - FOOT_PLANE * scale;
    }

    public void render(PoseStack poseStack, VertexConsumer buffer, int light) {
        this.root.render(poseStack, buffer, light, OverlayTexture.NO_OVERLAY);
    }
}
