#!/usr/bin/env python3
"""Convert art/dragon_form.bbmodel into the mod's model class and textures.

Usage:  python3 tools/bbmodel_to_java.py [art/dragon_form.bbmodel]

See tools/README.md for the coordinate conventions applied.
"""
import base64
import io
import json
import math
import os
import re
import sys

from PIL import Image

GROUND = 96.0          # bb y of the model's foot plane in the authoring rig
ROOTS = ("head", "body", "right_arm", "left_arm", "right_leg", "left_leg")
RENAME = {"canon_head_REFERENCE": "skull", "ref_jaw": "jaw"}
VANILLA_PIVOTS = {
    "head": (0.0, 0.0, 0.0), "body": (0.0, 0.0, 0.0),
    "right_arm": (-5.0, 2.0, 0.0), "left_arm": (5.0, 2.0, 0.0),
    "right_leg": (-1.9, 12.0, 0.0), "left_leg": (1.9, 12.0, 0.0),
}
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JAVA_OUT = os.path.join(HERE, "src/main/java/com/enderdragonanthro/client/model/DragonFormModel.java")
TEX_DIR = os.path.join(HERE, "src/main/resources/assets/enderdragonanthro/textures/entity")
RIG_OUT = os.path.join(HERE, "src/main/java/com/enderdragonanthro/DragonRig.java")

# The wings are a mirror pair sharing one UV region, and Blockbench flags the
# -x twin with mirror_uv. In Minecraft that flag is redundant AND harmful.
#
# A cube's u runs from its box origin to origin+size. wing_left spans x 16..72,
# so its low-u end is INBOARD; wing_right spans x -72..-16, so its low-u end is
# OUTBOARD. The pair therefore already runs its texture in opposite directions
# with no flag at all -- which is exactly the mirroring a symmetric pair wants.
# Adding .mirror() on top of that mirrors it a second time.
#
# The evidence, from two builds: with mirror_uv ignored entirely, wing_right
# rendered correctly and wing_left came out with its inner and tip panels
# swapped end-for-end (the membrane read "ng][wi" instead of "[wing]").
# Honouring mirror_uv then broke wing_right the same way. So the art is painted
# low-u = OUTBOARD: wing_right gets that for free and wing_left is the one that
# needs flipping.
#
# Scoped to the wings by name rather than applied as a rule, because the
# handedness the art was painted for is a fact about the art, not about the
# geometry -- there is nothing in the model to derive it from.
MIRROR_OVERRIDE = {
    # The arms have the same disease as the wings, caught later and only on
    # half the pieces. Same rule: a cube's u runs from its box origin, so the
    # -x twin gets low-u = OUTBOARD for free and the +x twin has to be flipped
    # to match. Every left-arm cube therefore wants the flag.
    #
    # In the rig only delt_left and fist_left carry mirror_uv; upper_arm_left
    # and forearm_left do not. So two pieces of the left arm ran their texture
    # one way and two ran it the other, on the same limb -- which is what makes
    # it read as broken from any angle, and in first person, where that arm is
    # what the player's right hand shows.
    "delt_left": True,
    "upper_arm_left": True,
    "forearm_left": True,
    "delt_right": False,
    "upper_arm_right": False,
    "forearm_right": False,

    # The fists go the other way, and the rule above does not predict it -- the
    # rule was reasoned from where a cube's u starts and never tested against
    # anything, because the arm pieces are plain hide and a reversed u on plain
    # hide is invisible. The fists are the first pieces of that limb carrying
    # art with a direction to it, and in game each hand was wearing the other
    # one's claw. Mirrored exactly once either way, so check_mirror_pairs was
    # always going to pass; it is the wrong twin that carried the flag.
    #
    # This does mean a fist now runs its u opposite to the forearm above it.
    # That is invisible on hide with no direction and glaring on a claw, which
    # is the whole reason to let the eye settle it rather than the rule.
    "fist_left": False,
    "fist_right": True,

    # And the legs, which verify_model found the moment it was taught to look:
    # thigh and calf were unmirrored on both sides, foot was mirrored on both.
    # Every one of these pairs is a clean +-x mirror, so the rule is the same
    # for all of them and there is no judgement left to make.
    "thigh_left": True,
    "calf_left": True,
    "foot_left": True,
    "thigh_right": False,
    "calf_right": False,
    "foot_right": False,

    "wing_bone_left": True,
    "wing_membrane_left": True,
    "wing_tip_bone_left": True,
    "wing_tip_membrane_left": True,
    "wing_bone_right": False,
    "wing_membrane_right": False,
    "wing_tip_bone_right": False,
    "wing_tip_membrane_right": False,
}


RIG_TEMPLATE = '''package com.enderdragonanthro;

/**
 * GENERATED by tools/bbmodel_to_java.py — do not hand-edit.
 *
 * The rig's own measurements, on the common side because the eye height they
 * feed is part of the entity's dimensions and so has to agree on the server as
 * well as the client.
 */
public final class DragonRig {{
    /** The rig's foot plane, and the top of the skull above it, in model units. */
    public static final float FOOT_PLANE = {ground}F;
    public static final float SKULL_HEIGHT = {skull}F;

    /**
     * Centre of the painted eyes, in model units above the foot plane, read
     * off the emissive sheet at conversion time. Paint the eyes somewhere else
     * and this follows them.
     */
    public static final float EYE_RIG_Y = {eye}F;

    /** The model is authored at four times life size on the sheet. */
    public static final float AUTHORED_SCALE = 4.0F;
    /** Exactly as drawn: the head rides above the hitbox, as the canon dragon's does. */
    public static final float TRUE_SCALE = 1.0F / AUTHORED_SCALE;
    /** Trimmed so the skull tops out level with the hitbox. */
    public static final float RENDER_SCALE = 1.8F * 16.0F / SKULL_HEIGHT;

    private DragonRig() {{
    }}

    /**
     * The rig puts the foot plane at FOOT_PLANE, which only lands on the ground
     * at a scale of exactly 0.25. Any other scale lifts the whole dragon, so
     * the layer drops it back by this much before drawing.
     */
    public static float groundOffset(float scale) {{
        return 24.0F - FOOT_PLANE * scale;
    }}

    /**
     * The eye height, as a fraction of hitbox height, that lands the camera on
     * the painted eyes.
     *
     * The entity scale cancels — the eye is a fraction of the hitbox and the
     * model is a multiple of the same scale — so this depends on the render
     * scale alone. That cancellation is exactly why vanilla's fixed 0.9 can
     * never track the model: nothing in it refers to the rig.
     */
    public static double eyeRatio(float renderScale) {{
        return EYE_RIG_Y * renderScale / (16.0 * 1.8);
    }}
}}
'''


def measure_eyes(bb, glow):
    """Rig height of the painted eyes, read off the emissive sheet.

    So the camera can be put where the eyes are instead of at vanilla's fixed
    0.9 of the hitbox, which knows nothing about the model.
    """
    px = glow.load()
    lit = [(x, y) for y in range(glow.height) for x in range(glow.width)
           if px[x, y][3] > 0]
    best = None
    for e in bb["elements"]:
        if e.get("type", "cube") != "cube":
            continue
        if any(abs(t) > 1e-9 for t in e.get("rotation", [0, 0, 0])):
            continue                 # a rotated eye would need the whole pivot chain
        u, v = e["uv_offset"]
        w, h, d = [e["to"][i] - e["from"][i] for i in range(3)]
        if w <= 0 or h <= 0:
            continue
        fx, fy = u + d, v + d        # the north (front) face
        rows = [p[1] for p in lit if fx <= p[0] < fx + w and fy <= p[1] < fy + h]
        if not rows:
            continue
        top, bot = e["to"][1], e["from"][1]
        span = (top - (max(rows) + 1 - fy) / h * (top - bot),
                top - (min(rows) - fy) / h * (top - bot))
        if best is None or span[1] > best[1]:
            best = span              # the highest lit face is the face
    return best


def wants_mirror(e):
    """Blockbench's mirror_uv, except where the wings override it."""
    return MIRROR_OVERRIDE.get(e.get("name", ""), bool(e.get("mirror_uv")))


def jy(v):
    return GROUND - v


def jpivot(o):
    return (round(o[0], 4), round(jy(o[1]), 4), round(o[2], 4))


def jrot(r):
    """Blockbench degrees -> Java radians.

    Java model space is Blockbench's with Y flipped, so a part's rotation must
    satisfy R_java = M * R_bb * M for M = diag(1,-1,1). Conjugating each axis
    by M gives Rx(-x), Ry(+y), Rz(-z): X and Z flip sign, Y is unchanged.
    """
    return (round(-math.radians(r[0]), 4),
            round(math.radians(r[1]), 4),
            round(-math.radians(r[2]), 4))


def jbox(e):
    f, t = e["from"], e["to"]
    return ((round(f[0], 4), round(jy(t[1]), 4), round(f[2], 4)),
            tuple(round(t[i] - f[i], 4) for i in range(3)))


def convert(path):
    bb = json.load(open(path))
    groups = {g["uuid"]: g for g in bb.get("groups", [])}
    els = {e["uuid"]: e for e in bb["elements"]}
    lines, used = [], set()
    # The extent of the arm the first-person hand clones, so it can be fitted
    # from the rig rather than from numbers typed in by hand.
    #
    # That is the rig's LEFT arm. The rig names its arms from the model's own
    # facing, which is the mirror of the game's, so the part called left_arm is
    # the one that reads as the player's right hand -- and the right hand is
    # what first person shows.
    arm = {}
    # Topmost point of the skull group, in java y, so the rig's own height
    # drives the scaling instead of a number typed in once.
    tops = {}

    def ident(name):
        s = re.sub(r"\W", "_", name)
        s = s[0].lower() + s[1:]
        while s in used:
            s += "_"
        used.add(s)
        return s

    def emit(node, parent_var, parent_pivot):
        g = groups.get(node["uuid"], {})
        name = RENAME.get(g.get("name", "?"), g.get("name", "?"))
        piv = jpivot(g.get("origin", [0, 0, 0]))
        rot = jrot(g.get("rotation", [0, 0, 0]))
        off = tuple(round(piv[i] - parent_pivot[i], 4) for i in range(3))
        cubes = [els[c] for c in node.get("children", []) if isinstance(c, str) and c in els]
        kids = [c for c in node.get("children", []) if not isinstance(c, str)]

        # A ModelPart's cubes are axis-aligned within it, so a cube that carries
        # its own rotation in Blockbench cannot live in this part's cube list —
        # it becomes a one-cube child part pivoted on the cube's own origin.
        # mirror_uv flips a cube's texture horizontally. Two cubes mirrored in
        # world space share one UV region, so without this the asymmetric art
        # lands reversed on one side. See MIRROR_OVERRIDE for the wings, where
        # the flag has to be taken the other way round.
        boxes, spun, mirrored = [], [], False
        for e in cubes:
            u, v = e["uv_offset"]
            (x, y, z), (w, h, d) = jbox(e)
            tex = f".texOffs({int(round(u))}, {int(round(v))})"
            want = wants_mirror(e)
            if any(abs(t) > 1e-9 for t in e.get("rotation", [0, 0, 0])):
                spun.append((e, tex, (x, y, z), (w, h, d), want))
            else:
                prefix = ""
                if want != mirrored:
                    prefix = f".mirror({'true' if want else 'false'})"
                    mirrored = want
                boxes.append(f"{prefix}{tex}.addBox({x - piv[0]:.3f}F, {y - piv[1]:.3f}F, "
                             f"{z - piv[2]:.3f}F, {w:.3f}F, {h:.3f}F, {d:.3f}F)")
                if name == "skull":
                    tops["skull"] = min(tops.get("skull", y), y)
                if name == "left_arm":
                    lo = (x - piv[0], y - piv[1], z - piv[2])
                    hi = (lo[0] + w, lo[1] + h, lo[2] + d)
                    for i in range(3):
                        arm[f"lo{i}"] = min(arm.get(f"lo{i}", lo[i]), lo[i])
                        arm[f"hi{i}"] = max(arm.get(f"hi{i}", hi[i]), hi[i])
        if mirrored:
            boxes.append(".mirror(false)")
        cl = "CubeListBuilder.create()" if not boxes else \
            "CubeListBuilder.create()\n" + "\n".join(" " * 24 + b for b in boxes)
        pose = (f"PartPose.offset({off[0]:.3f}F, {off[1]:.3f}F, {off[2]:.3f}F)"
                if rot == (0.0, 0.0, 0.0) else
                f"PartPose.offsetAndRotation({off[0]:.3f}F, {off[1]:.3f}F, {off[2]:.3f}F, "
                f"{rot[0]:.4f}F, {rot[1]:.4f}F, {rot[2]:.4f}F)")
        if kids or spun:
            var = ident(name)
            lines.append(f'        PartDefinition {var} = {parent_var}.addOrReplaceChild("{name}", {cl},\n'
                         f"                {pose});")
            for e, tex, (x, y, z), (w, h, d), want in spun:
                o = jpivot(e.get("origin", [0, 0, 0]))
                r = jrot(e["rotation"])
                sub = ident(f"{name}_spin")
                tex = (".mirror(true)" if want else "") + tex
                lines.append(
                    f'        {var}.addOrReplaceChild("{sub}", CubeListBuilder.create()\n'
                    f"                        {tex}.addBox({x - o[0]:.3f}F, {y - o[1]:.3f}F, "
                    f"{z - o[2]:.3f}F, {w:.3f}F, {h:.3f}F, {d:.3f}F),\n"
                    f"                PartPose.offsetAndRotation({o[0] - piv[0]:.3f}F, "
                    f"{o[1] - piv[1]:.3f}F, {o[2] - piv[2]:.3f}F, "
                    f"{r[0]:.4f}F, {r[1]:.4f}F, {r[2]:.4f}F));")
            for k in kids:
                emit(k, var, piv)
        else:
            lines.append(f'        {parent_var}.addOrReplaceChild("{name}", {cl},\n'
                         f"                {pose});")

    res = bb.get("resolution", {"width": 512, "height": 512})
    for e in bb["elements"]:
        u, v = e["uv_offset"]
        w, h, d = [e["to"][i] - e["from"][i] for i in range(3)]
        fw, fh = 2 * (w + d), d + h
        if u < 0 or v < 0 or u + fw > res["width"] or v + fh > res["height"]:
            print(f"  WARNING: {e['name']} unwrap runs off the sheet at uv({u},{v}) "
                  f"— those faces sample clamped pixels in game")

    roots = {groups[n["uuid"]].get("name"): n for n in bb["outliner"]}
    missing = [r for r in ROOTS if r not in roots]
    if missing:
        sys.exit(f"ERROR: model is missing required root group(s): {missing}")

    for nm in ROOTS:
        lines.append(f"\n        // ---- {nm} ----")
        emit(roots[nm], "root", (0.0, 0.0, 0.0))
    body_pivot = jpivot(groups[roots["body"]["uuid"]]["origin"])
    wings = [w for w in ("wing_right", "wing_left") if w in roots]
    if wings:
        lines.append("\n        // ---- wings: re-parented onto body so they follow the torso ----")
        for nm in wings:
            emit(roots[nm], "body", body_pivot)

    pivots = {nm: jpivot(groups[roots[nm]["uuid"]]["origin"]) for nm in ROOTS}
    base = "\n".join(f"    private static final float[] BASE_{k.upper()} = "
                     f"{{{v[0]:.3f}F, {v[1]:.3f}F, {v[2]:.3f}F}};" for k, v in pivots.items())
    vanilla = "\n".join(f"    private static final float[] V_{k.upper()} = "
                        f"{{{v[0]}F, {v[1]}F, {v[2]}F}};" for k, v in VANILLA_PIVOTS.items())

    if len(arm) != 6:
        sys.exit("ERROR: could not measure left_arm; the first-person hand needs it")
    # Java y counts downward from the foot plane, so the topmost point is the
    # smallest value. Fall back to the whole rig if the skull group is missing.
    top = tops.get("skull", GROUND - 136.0)
    skull_height = GROUND - top
    java = TEMPLATE.format(base=base, vanilla=vanilla, parts="\n".join(lines),
                           tw=res["width"], th=res["height"],
                           ground=f"{GROUND:.1f}", skull=f"{skull_height:.1f}",
                           ax0=f"{arm['lo0']:.3f}", ax1=f"{arm['hi0']:.3f}",
                           ay0=f"{arm['lo1']:.3f}", ay1=f"{arm['hi1']:.3f}",
                           az0=f"{arm['lo2']:.3f}", az1=f"{arm['hi2']:.3f}")
    os.makedirs(TEX_DIR, exist_ok=True)
    img = Image.open(io.BytesIO(base64.b64decode(
        bb["textures"][0]["source"].split(",", 1)[1]))).convert("RGBA")
    img.save(os.path.join(TEX_DIR, "dragon_form.png"))

    glow = Image.new("RGBA", img.size, (0, 0, 0, 0))
    gp, ip, lit = glow.load(), img.load(), 0
    for y in range(img.height):
        for x in range(img.width):
            r, g, b, a = ip[x, y]
            if a > 0 and r > 90 and b > 120 and g < r * 0.75 and (r + b) > g * 2.2:
                gp[x, y] = (r, g, b, 255)
                lit += 1
    glow.save(os.path.join(TEX_DIR, "dragon_form_eyes.png"))

    eyes = measure_eyes(bb, glow)
    eye_y = sum(eyes) / 2 if eyes else skull_height * 0.9

    os.makedirs(os.path.dirname(JAVA_OUT), exist_ok=True)
    open(JAVA_OUT, "w").write(java)
    open(RIG_OUT, "w").write(RIG_TEMPLATE.format(
        ground=f"{GROUND:.1f}", skull=f"{skull_height:.1f}", eye=f"{eye_y:.2f}"))

    print(f"{len(bb['elements'])} cubes -> {java.count('addOrReplaceChild')} parts")
    print(f"textures written ({lit} emissive pixels)")
    trim = 1.8 * 16.0 / skull_height
    print(f"rig height: {skull_height:.1f} model units, foot plane to the top of the skull")
    if eyes:
        print(f"painted eyes: rig y {eyes[0]:.1f}..{eyes[1]:.1f}, centre {eye_y:.1f}")
    print(f"  trueProportions on  -> drawn {skull_height * 0.25 / 16 * (8 / 1.8):.2f} blocks "
          f"at an 8-block hitbox   (rig height shows)")
    print(f"  trueProportions off -> drawn {skull_height * trim / 16 * (8 / 1.8):.2f} blocks "
          f"at an 8-block hitbox   (rig height normalised away)")


TEMPLATE = '''package com.enderdragonanthro.client.model;

import com.enderdragonanthro.DragonRig;
import com.enderdragonanthro.EnderdragonAnthro;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.PlayerModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.player.AbstractClientPlayer;
import net.minecraft.client.renderer.texture.OverlayTexture;

/**
 * The anthro dragon. GENERATED by tools/bbmodel_to_java.py from
 * art/dragon_form.bbmodel — do not hand-edit; re-run the converter instead.
 *
 * Authored at 4x on a {tw}x{th} sheet and drawn at {{@link #RENDER_SCALE}},
 * which both restores real size and buys one texel per model unit. The six
 * root parts keep the player's bone names and copy their poses every frame,
 * so all vanilla animation drives this body.
 */
public class DragonFormModel {{
    public static final ModelLayerLocation LAYER =
            new ModelLayerLocation(EnderdragonAnthro.id("dragon_form"), "main");

    /** Model units are 4x final units. */
    public static final float AUTHOR_SCALE = 4.0F;


    /**
     * Re-exported from DragonRig, which is where the rig's measurements live —
     * the eye height they feed is part of the entity's dimensions, so the
     * server needs them too. Restating them here is what put this preview
     * eight units out once already.
     */
    public static final float TRUE_SCALE = DragonRig.TRUE_SCALE;
    public static final float RENDER_SCALE = DragonRig.RENDER_SCALE;

    public static float groundOffset(float scale) {{
        return DragonRig.groundOffset(scale);
    }}

    /**
     * The box of the arm the first-person hand clones, in that part's local
     * space, measured off the rig at conversion time.
     *
     * That arm is the rig's left_arm. The rig names its arms from the model's
     * own facing, which is the mirror of the game's, so the part called
     * left_arm is the one that reads as the player's RIGHT hand -- and the
     * right hand is what first person shows. Fitted from these numbers, so
     * reshaping the arm in Blockbench moves the hand with it.
     */
    public static final float ARM_MIN_X = {ax0}F;
    public static final float ARM_MAX_X = {ax1}F;
    public static final float ARM_MIN_Y = {ay0}F;
    public static final float ARM_MAX_Y = {ay1}F;
    public static final float ARM_MIN_Z = {az0}F;
    public static final float ARM_MAX_Z = {az1}F;

    /**
     * Scaled so the dragon's arm is as long on screen as the human one it
     * replaces — the vanilla arm is 12 model units from shoulder to fingertip.
     */
    public static final float ARM_SCALE = 12.0F / (ARM_MAX_Y - ARM_MIN_Y);

{base}

    // the vanilla player pivots these parts track
{vanilla}

    private final ModelPart root;
    private final ModelPart head;
    private final ModelPart body;
    private final ModelPart rightArm;
    private final ModelPart leftArm;
    private final ModelPart rightLeg;
    private final ModelPart leftLeg;

    public DragonFormModel(ModelPart root) {{
        this.root = root;
        this.head = root.getChild("head");
        this.body = root.getChild("body");
        this.rightArm = root.getChild("right_arm");
        this.leftArm = root.getChild("left_arm");
        this.rightLeg = root.getChild("right_leg");
        this.leftLeg = root.getChild("left_leg");
    }}

    public static LayerDefinition createLayer() {{
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
{parts}

        return LayerDefinition.create(mesh, {tw}, {th});
    }}

    /**
     * Ride the vanilla skeleton. Positions are applied as a DELTA from the
     * player's own rest pivots rather than copied outright, because this
     * model's pivots are not simply the player's times four — the legs are
     * longer, which lifts everything. Copying outright would tear the body
     * apart; the delta still picks up animated offsets such as sneaking.
     */
    public void copyPose(PlayerModel<AbstractClientPlayer> m) {{
        apply(this.head, m.head, BASE_HEAD, V_HEAD);

        apply(this.body, m.body, BASE_BODY, V_BODY);
        apply(this.rightArm, m.rightArm, BASE_RIGHT_ARM, V_RIGHT_ARM);
        apply(this.leftArm, m.leftArm, BASE_LEFT_ARM, V_LEFT_ARM);
        apply(this.rightLeg, m.rightLeg, BASE_RIGHT_LEG, V_RIGHT_LEG);
        apply(this.leftLeg, m.leftLeg, BASE_LEFT_LEG, V_LEFT_LEG);
        rideTorso();
    }}

    /**
     * Give the head the neck it actually has.
     *
     * A player's head is a cube resting on a flat chest with no neck between
     * them, so vanilla can leave the two as separate root parts: crouching
     * pitches the body 0.5 rad, drops the head by a hand-tuned 4.2, and the
     * seam never shows because there is no seam to show.
     *
     * This rig has a neck, and it is hidden by being buried: the neck spans rig
     * y 105-117 and the chest 89-109, so four units of it live inside the chest.
     * Both groups pivot on the same point, y 109. So when the body pitched and
     * the head did not, the chest rotated straight off the neck and left the
     * stump standing in the open.
     *
     * Because the two pivots coincide, handing the head the body's rotation is
     * exactly equivalent to parenting it to the body -- no translation needed,
     * and the buried four units stay buried through any pose the body takes.
     * The look angles still add on top, so aiming is untouched.
     *
     * Standing, this is a no-op: vanilla zeroes both offsets and the body's
     * pitch, so every term here is zero.
     */
    private void rideTorso() {{
        this.head.y = this.body.y;
        this.head.z = this.body.z;
        this.head.xRot += this.body.xRot;
        this.head.yRot += this.body.yRot;
        this.head.zRot += this.body.zRot;
    }}

    private static void apply(ModelPart target, ModelPart source, float[] base, float[] vanilla) {{
        target.copyFrom(source);
        target.x = base[0] + (source.x - vanilla[0]) * AUTHOR_SCALE;
        target.y = base[1] + (source.y - vanilla[1]) * AUTHOR_SCALE;
        target.z = base[2] + (source.z - vanilla[2]) * AUTHOR_SCALE;
    }}

    public void render(PoseStack poseStack, VertexConsumer buffer, int light) {{
        this.root.render(poseStack, buffer, light, OverlayTexture.NO_OVERLAY);
    }}

    /**
     * One arm on its own, shoulder at the origin, for the first-person hand.
     *
     * Its pivot and pose are neutralised for the duration: in first person the
     * arm is placed by the hand renderer, not by the body it belongs to.
     */
    public void renderArm(boolean right, PoseStack poseStack, VertexConsumer buffer, int light) {{
        ModelPart arm = right ? this.rightArm : this.leftArm;
        float x = arm.x, y = arm.y, z = arm.z;
        float xRot = arm.xRot, yRot = arm.yRot, zRot = arm.zRot;
        arm.setPos(0.0F, 0.0F, 0.0F);
        arm.setRotation(0.0F, 0.0F, 0.0F);
        arm.render(poseStack, buffer, light, OverlayTexture.NO_OVERLAY);
        arm.setPos(x, y, z);
        arm.setRotation(xRot, yRot, zRot);
    }}
}}
'''

if __name__ == "__main__":
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "art/dragon_form.bbmodel")
    convert(src)
