#!/usr/bin/env python3
"""Convert art/shade_base.bbmodel into the court's model class.

    python3 tools/shade_to_java.py

Same conventions as bbmodel_to_java.py -- it imports that file's coordinate
helpers rather than restating them -- but a much smaller job, because the shade
rig is six bones and nine cubes rather than seventy-five.

The six bones are deliberately the ones HumanoidModel has: EndermanModel
extends HumanoidModel, so a shade can ride the vanilla enderman's animation the
same way the dragon rides the player's. Copy the six rotations across each
frame and every walk cycle, attack swing and carry pose comes free.

Never hand-edit the generated file. A constant added there survives exactly
until the next conversion; put it in TEMPLATE below.
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bbmodel_to_java import jbox, jpivot, jrot, jy, bake, CLIP_SAMPLES   # noqa: E402
from pack_shade_rig import AUTHOR_SCALE              # noqa: E402

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RIG = os.path.join(HERE, "art/shade_base.bbmodel")
OUT = os.path.join(HERE,
                   "src/main/java/com/enderdragonanthro/client/model/ShadeModel.java")

BONES = ("head", "body", "right_arm", "left_arm", "right_leg", "left_leg")
FIELD = {"head": "head", "body": "body", "right_arm": "rightArm",
         "left_arm": "leftArm", "right_leg": "rightLeg", "left_leg": "leftLeg"}

#: The clips the rig may carry, and the field each is baked into. A clip the
#: rig does not have comes out as an empty table and plays as nothing, which is
#: what should happen to an animation nobody has drawn yet.
CLIPS = (("idle", "IDLE"), ("walk", "WALK"), ("carry", "CARRY"),
         ("angry", "ANGRY"), ("pet", "PET"))


def clips(bb):
    """Every animation in the rig, baked to sample tables and Java source."""
    out, ticks = [], []
    for clip, field in CLIPS:
        baked = bake(bb, clip, BONES, require_all=False)
        rows = len(BONES) * 6
        if baked is None:
            ticks.append(f"    public static final int {field}_TICKS = 0;")
            out.append(f"    private static final float[][] {field} = new float[{rows}][];")
            continue
        length, tracks = baked
        ticks.append(f"    public static final int {field}_TICKS = {length};")
        out.append(f"    private static final float[][] {field} = new float[{rows}][];")
        out.append("")
        out.append("    static {")
        for (bone, channel, axis), samples in sorted(tracks.items()):
            row = BONES.index(bone) * 6 + (0 if channel == "rotation" else 3) + "xyz".index(axis)
            body = ", ".join(f"{v:.5f}F" for v in samples)
            out.append(f"        {field}[{row}] = new float[] {{{body}}};"
                       f"   // {bone}.{channel}.{axis}")
        out.append("    }")
        out.append("")
    return "\n".join(ticks) + "\n\n" + "\n".join(out)


TEMPLATE = '''package com.enderdragonanthro.client.model;

import com.enderdragonanthro.EnderdragonAnthro;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.renderer.texture.OverlayTexture;
import net.minecraft.util.Mth;
import net.minecraft.world.entity.LivingEntity;

/**
 * GENERATED by tools/shade_to_java.py from art/shade_base.bbmodel.
 * Do not hand-edit: the next conversion overwrites it.
 *
 * One of the court, drawn over a vanilla enderman. The bones are named for
 * HumanoidModel's, which EndermanModel extends, so copyPose can hand this rig
 * the vanilla animation and every walk cycle and carry pose comes free.
 */
public class ShadeModel {{
    public static final ModelLayerLocation LAYER =
            new ModelLayerLocation(EnderdragonAnthro.id("shade"), "main");

    /** The rig is drawn {author}x oversize to buy texel density; undo it here. */
    public static final float AUTHOR_SCALE = {author}.0F;
    public static final float TRUE_SCALE = 1.0F / AUTHOR_SCALE;
    /** Java y of the foot plane, before that scale. */
    public static final float FOOT_PLANE = {foot}F;

    private final ModelPart root;
    private final ModelPart head;
    private final ModelPart body;
    private final ModelPart rightArm;
    private final ModelPart leftArm;
    private final ModelPart rightLeg;
    private final ModelPart leftLeg;

    public ShadeModel(ModelPart root) {{
        this.root = root;
        this.head = root.getChild("head");
        this.body = root.getChild("body");
        this.rightArm = root.getChild("right_arm");
        this.leftArm = root.getChild("left_arm");
        this.rightLeg = root.getChild("right_leg");
        this.leftLeg = root.getChild("left_leg");
    }}

    public static LayerDefinition createBodyLayer() {{
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

{parts}
        return LayerDefinition.create(mesh, {tw}, {th});
    }}

    /**
     * Take the vanilla enderman's pose.
     *
     * Rotations only. Positions are this rig's own, because a shade's shoulders
     * and hips are nowhere near an enderman's -- copying those outright tears
     * the body apart, which is the same lesson the dragon's copyPose records.
     */
    public void copyPose(HumanoidModel<? extends LivingEntity> from) {{
        rot(this.head, from.head);
        rot(this.body, from.body);
        rot(this.rightArm, from.rightArm);
        rot(this.leftArm, from.leftArm);
        rot(this.rightLeg, from.rightLeg);
        rot(this.leftLeg, from.leftLeg);
    }}

    /**
     * The head bone, already posed, for anything that rides on her face.
     *
     * Its pivot is the artist's and moves whenever the rig does -- the head
     * dropped a notch once already -- so a shell copying this part follows it,
     * where one built on typed-in numbers quietly drifts off her face.
     */
    public ModelPart head() {{
        return this.head;
    }}

    private static void rot(ModelPart target, ModelPart source) {{
        target.xRot = source.xRot;
        target.yRot = source.yRot;
        target.zRot = source.zRot;
    }}

    // ------------------------------------------------------------- animation

    /** Samples each baked clip holds across one cycle. */
    private static final int CLIP_SAMPLES = {samples};

{clips}
    /** The bones a clip can move, in the order the tables are laid out. */
    private ModelPart[] bones() {{
        return new ModelPart[] {{this.head, this.body, this.rightArm,
                                this.leftArm, this.rightLeg, this.leftLeg}};
    }}

    /**
     * Play one clip over whatever copyPose left behind.
     *
     * Blended from the current rotation rather than written over it, so a
     * weight below one is a crossfade between the enderman's pose and the
     * artist's -- which is what lets a shade ease into a stride instead of
     * snapping into one. At weight 0 nothing is touched at all.
     *
     * A channel the clip does not key is LEFT ALONE rather than driven to rest.
     * That is the difference between "the artist did not animate the head" and
     * "the artist wants the head at zero", and getting it the other way round
     * would throw away vanilla's head tracking the moment anyone drew a walk
     * cycle. Every bone in this rig rests at zero, so a keyed value is both a
     * delta and an absolute angle and the animator shows exactly what plays.
     */
    public void play(float[][] clip, float phase, float weight) {{
        if (weight <= 0.0F || clip.length == 0) {{
            return;
        }}
        float at = Mth.positiveModulo(phase, 1.0F) * CLIP_SAMPLES;
        int lo = (int) at;
        int hi = (lo + 1) % CLIP_SAMPLES;
        float f = at - lo;
        ModelPart[] bones = bones();
        for (int b = 0; b < bones.length; b++) {{
            ModelPart bone = bones[b];
            float[] x = clip[b * 6];
            float[] y = clip[b * 6 + 1];
            float[] z = clip[b * 6 + 2];
            if (x != null) {{
                bone.xRot = Mth.lerp(weight, bone.xRot, Mth.lerp(f, x[lo], x[hi]));
            }}
            if (y != null) {{
                bone.yRot = Mth.lerp(weight, bone.yRot, Mth.lerp(f, y[lo], y[hi]));
            }}
            if (z != null) {{
                bone.zRot = Mth.lerp(weight, bone.zRot, Mth.lerp(f, z[lo], z[hi]));
            }}
        }}
    }}

    /** The clips, by the name the rig calls them. Empty means nobody drew one. */
    public static float[][] clip(Clip which) {{
        return switch (which) {{
            case IDLE -> IDLE;
            case WALK -> WALK;
            case CARRY -> CARRY;
            case ANGRY -> ANGRY;
            case PET -> PET;
        }};
    }}

    /** How long each runs, in ticks. Zero means the rig carries no such clip. */
    public static int ticks(Clip which) {{
        return switch (which) {{
            case IDLE -> IDLE_TICKS;
            case WALK -> WALK_TICKS;
            case CARRY -> CARRY_TICKS;
            case ANGRY -> ANGRY_TICKS;
            case PET -> PET_TICKS;
        }};
    }}

    /** What a shade can be doing, as far as the rig is concerned. */
    public enum Clip {{
        IDLE, WALK, CARRY, ANGRY, PET
    }}

    /**
     * The rig puts its feet at FOOT_PLANE, which only lands on the ground at a
     * scale of exactly one over AUTHOR_SCALE. Any other scale lifts the whole
     * body, so the layer drops it back by this much before drawing.
     */
    public static float groundOffset(float scale) {{
        return 24.0F - FOOT_PLANE * scale;
    }}

    public void render(PoseStack poseStack, VertexConsumer buffer, int light) {{
        this.root.render(poseStack, buffer, light, OverlayTexture.NO_OVERLAY);
    }}
}}
'''


def main():
    with open(RIG) as f:
        bb = json.load(f)

    groups = {g["uuid"]: g for g in bb.get("groups", [])}
    els = {e["uuid"]: e for e in bb["elements"]}

    lines = []
    for node in bb["outliner"]:
        g = groups.get(node["uuid"], {})
        name = g.get("name")
        if name not in BONES:
            continue
        piv = jpivot(g.get("origin", [0, 0, 0]))
        boxes, spun = [], []
        for cid in node.get("children", []):
            e = els.get(cid) if isinstance(cid, str) else None
            if not e:
                continue
            (x, y, z), (w, h, d) = jbox(e)
            tex = ".texOffs({}, {})".format(*[int(round(c)) for c in e["uv_offset"]]) \
                if "uv_offset" in e else ".texOffs(0, 0)"
            mirror = ".mirror(true)" if e.get("mirror_uv") else ""
            box = (f'{mirror}{tex}.addBox({x - piv[0]:.3f}F, {y - piv[1]:.3f}F, '
                   f'{z - piv[2]:.3f}F, {w:.3f}F, {h:.3f}F, {d:.3f}F)')
            rot = e.get("rotation") or [0, 0, 0]
            if any(abs(t) > 1e-9 for t in rot):
                # Minecraft cannot rotate one cube inside a part, so it becomes
                # its own child pivoted on the cube's own origin.
                cpiv = jpivot(e.get("origin", [0, 0, 0]))
                crot = jrot(rot)
                spun.append((e.get("name", "spun"), cpiv, crot, mirror, tex,
                             (x - cpiv[0], y - cpiv[1], z - cpiv[2]), (w, h, d)))
            else:
                boxes.append(box)

        cl = "CubeListBuilder.create()" + ("\n                        " .join([""] + boxes)
                                           if boxes else "")
        lines.append(f'        PartDefinition {name} = root.addOrReplaceChild("{name}", {cl},')
        lines.append(f'                PartPose.offset({piv[0]:.3f}F, {piv[1]:.3f}F, {piv[2]:.3f}F));')
        for i, (cname, cpiv, crot, mirror, tex, off, size) in enumerate(spun):
            child = f"{name}_{i}"
            lines.append(f'        {name}.addOrReplaceChild("{child}", CubeListBuilder.create()')
            lines.append(f'                        {mirror}{tex}.addBox({off[0]:.3f}F, {off[1]:.3f}F, '
                         f'{off[2]:.3f}F, {size[0]:.3f}F, {size[1]:.3f}F, {size[2]:.3f}F),')
            lines.append(f'                PartPose.offsetAndRotation({cpiv[0] - piv[0]:.3f}F, '
                         f'{cpiv[1] - piv[1]:.3f}F, {cpiv[2] - piv[2]:.3f}F, '
                         f'{crot[0]:.4f}F, {crot[1]:.4f}F, {crot[2]:.4f}F));')
        lines.append("")

    foot = max(jy(c) for e in bb["elements"] for c in (e["from"][1], e["to"][1]))
    res = bb["resolution"]
    out = TEMPLATE.format(parts="\n".join(lines), tw=res["width"], th=res["height"],
                          author=int(AUTHOR_SCALE), foot=f"{foot:.3f}",
                          clips=clips(bb), samples=CLIP_SAMPLES)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write(out)
    print(f"wrote {os.path.relpath(OUT, HERE)}")
    print(f"  {len(bb['elements'])} cubes, {len(BONES)} bones, "
          f"sheet {res['width']}x{res['height']}")
    print(f"  foot plane java y {foot:.2f}, drawn at 1/{int(AUTHOR_SCALE)}")


if __name__ == "__main__":
    main()
